steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - $_REGISTRY/$_REPOSITORY:${SHORT_SHA}
      - --build-arg
      - NODE_ENV=production
      - .
    id: Build

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGISTRY/$_REPOSITORY:${SHORT_SHA}']
    id: Push

