steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - $_REGISTRY/$_REPOSITORY:${SHORT_SHA}
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - $_REGISTRY/$_REPOSITORY:${SHORT_SHA}
options:
  substitution:
    _REGISTRY: 'REGION-docker.pkg.dev/PROJECT-ID'
    _REPOSITORY: 'firstname-studentid'
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
