steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/myproject-448803/zuhaib-100935821/$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/myproject-448803/zuhaib-100935821/$SHORT_SHA']

options:
  logging:'us-central1'

substitutions:
  _REGION: 'us-central1'

trigger:
  name: 'dc-zuhaib-100935821'
  event: 'push'
  branch: 'main'  # or the branch you want to trigger the build
  approvalRequired: true
