steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - $_REGISTRY/$_REPOSITORY:${SHORT_SHA}
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - $_REGISTRY/$_REPOSITORY:${SHORT_SHA}

substitutions:
  _REGISTRY: 'REGION-docker.pkg.dev/myproject-448803'
  _REPOSITORY: 'zuhaib-100935821'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
