steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$khan-191999/zuhaib-100935821/app:${COMMIT_SHA}'
      - '-f'
      - 'Dockerfile'  # Explicitly specify the Dockerfile
      - '.'  # Build context
