steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - $_REGISTRY/$_MY_REPO:${SHORT_SHA}
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - $_REGISTRY/$_MY_REPO:${SHORT_SHA}

substitutions:
  _REGISTRY: 'region-docker.pkg.dev/myproject-448803'
  _MY_REPO: 'zuhaib-100935821'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

